### ISSUE TITLE
1.0.3 Release Checklist

### ISSUE THREAD

**Issue by glennblock** [splunk/splunk-sdk-ruby#31]
# Splunk Master SDK Release Instructions

These are instructions on the various steps necessary to cut out a new
release of the Splunk Python SDK. Even though the instructions are public,
these steps are only meant to be taken by the SDK maintainers.
### Prerequisites
- [ ] Read through all of these release instructions.
  - Update if necessary. (For example, the version numbers will need updating.)
  - For updates that could apply to other SDKs as well, update the release instructions page for every other SDK.
- [ ] Update changelog.
- [ ] Run test suite on full test matrix.
- [ ] Run all examples.
- [ ] Run all dev.splunk.com code samples.
- [ ] Remove old temporary branches. This includes feature branches, old release branches, and most branches that have been merged to develop.
### Release Steps
- [ ] Create a release branch off of `develop`. This avoids problems if anyone else is merging code into `develop` while you are trying to release.
  - `git checkout develop`
  - `git branch release/1.0.3`
  - `git checkout release/1.0.3`
- [ ] Update the version number in the places it appears in the SDK:
  - `lib/splunk-sdk-ruby/version.rb`
  - `README.md`
  - `splunk-sdk-ruby.gemspec`
- [ ] Make sure the version number change didn't break anything:
  - Install the SDK in a clean VM.
  - Run test suite.
  - Run the SDK examples.
- [ ] Commit and run tests
  - Commit all changes you have made in this process to the `release/1.0.3` branch.
  - Run the test matrix in continuous integration on the `release/1.0.3` branch. Fix anything that broke and rerun until it all passes.
- [ ] Run the release script
  - Run the `release.rb` script in the root of the SDK repository. 
  - You may need to pass it the RubyGems username and password via the `--username` and `--password` options. (Our Splunk username and password for RubyGems are on [ESWiki](http://eswiki.splunk.com/Ruby_SDK_ERD#RubyGems)).
- [ ] Work with Docs team to:
  - Post ZIP file.
  - Update Readme. For point releases, the version number needs to be updated at a minimum.
  - Update Changelog, includes a list of changes for the current version.
  - Update Dev Portal and push. For point releases, the "What's new" page and download links need to be updated at the very least.
  - Publish API Reference (docs.splunk.com/Documentation/SDK).
  - Create both MD5 and SHA-512 hashes from _final_ ZIP download. Docs will contact the Web team to upload these files.
- [ ] Hand off to marketing to announce. See next section.
### Announce!

Hurrah, the new release is basically done! You can now announce it on the
following channels:
- Twitter (@splunkdev, maybe @splunk)
- Google Groups (splunkdev)
- Dev Portal (http://dev.splunk.com)
- Dev Blog (http://blogs.splunk.com/dev)
